spring.application.name=PigoPiVault
# ===============================
# MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/pivault
spring.datasource.username=root
spring.datasource.password=abhi5555
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8082

server.servlet.session.timeout=30m
#session object survive time means time gap b/w two req.

server.servlet.session.cookie.http-only=true
#when we send responce alongwith cookie to frontend {react,js etc} then we dont want to manuplate the cookie due to security reasons 
#prevent XSS attack : as we dont want to hacker push melisious code through the text box and hacker can't steal session id using JS

server.servelt.session.cookie.secure=false
#as of now we run on local server (tomcat) i.e http not https.when we deploy on server where https request supports then we change it to true

server.servlet.session.cookie.max-age=1800
#when the gap of 2 req above 1800 sec then browser kill the cookies

server.servlet.session.cookie.same-site=lax
#controls when cookies are sent in cross site requests.
#in real world frontend and backend may be not on same server.By default they denay the request from another server
#same origin request is OK(cookie send) ,frontend & backent same domain is also OK(cookie send)
#cross-site GET is OK(cookie send) but Cross site POST Req is NOT OK (cookie not send)

server.servlet.session.cookie.path=/
#cookie is valid for entire application thats route matches /

server.servlet.session.cookie.name=JSESSIONID
#special instruction to create cookie with this name (also default name for some browser )  



#############
#Url of froentend
app.frontend.url=http://localhost:3000

# Cloudinary

cloudinary.cloud-name=xifp6ege
cloudinary.api-key=889481862662543
cloudinary.api-secret=NojRJSYBEBc41HnGOKYvNsi7Ux0


# Multipart File Upload

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${keshriak555@gmail.com}
spring.mail.password=${kpch idau nfcz bozf}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
